{% macro prepend_generated_by() %}
----------------------------------------------------
-- Generated by DataUniversum                     --
-- https://datauniversum.com                      --
----------------------------------------------------
{%- endmacro -%}