version: 2

sources:
  - name: tpch_sf1
    description: '{{ doc("tpch_sf1") }}'
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    config:
      enabled: "{{ var('tpch_sf1_source_enabled') }}"

    tables:
      - name: customer
        description: '{{ doc("tpch_sf1_customer") }}'
        columns:
          - name: c_custkey
            description: '{{ doc("tpch_sf1_customer_c_custkey") }}'
          - name: c_name
            description: '{{ doc("tpch_sf1_customer_c_name") }}'
          - name: c_address
            description: '{{ doc("tpch_sf1_customer_c_address") }}'
          - name: c_nationkey
            description: '{{ doc("tpch_sf1_customer_c_nationkey") }}'
          - name: c_phone
            description: '{{ doc("tpch_sf1_customer_c_phone") }}'
          - name: c_acctbal
            description: '{{ doc("tpch_sf1_customer_c_acctbal") }}'
          - name: c_mktsegment
            description: '{{ doc("tpch_sf1_customer_c_mktsegment") }}'
          - name: c_comment
            description: '{{ doc("tpch_sf1_customer_c_comment") }}'

      - name: nation
        description: '{{ doc("tpch_sf1_nation") }}'
        columns:
          - name: n_nationkey
            description: '{{ doc("tpch_sf1_nation_n_nationkey") }}'
          - name: n_name
            description: '{{ doc("tpch_sf1_nation_n_name") }}'
          - name: n_comment
            description: '{{ doc("tpch_sf1_nation_n_comment") }}'
      - name: orders
        description: '{{ doc("tpch_sf1_orders") }}'